### ISSUE TITLE
encryption process

### ISSUE THREAD

**Issue by dadasane** [kaizhu256/node-demo-hls-encrypted#1]
Hi Kai Zhu. Can you please explain the entire encryption process from the MP4 file to the HLS encrypted version ( M3U8.ENCRYPED playlist and TS.ENCRYPTED segments) ? That would be wonderful !!!

**Comment by kaizhu256** [comment]
hi @dadasane, i added a file encrypt.sh and instructions in README.md on how to encrypt.  also star this repo if it was useful ;)

cheers!

**Comment by dadasane** [comment]
Hi Kai Zhu,
So I have downloaded and installed an Ubuntu VM....
I have encrypted your bunny video and it worked great...... 

I have tried with my own MP4 video that is 4min38 seconds...I had to tweak your encryt.sh .... I changed the input file and ended up with 46 TS unencrypted files and only 6 .TS.encrypted files.... I figured it is because of the FOR statement, so I tweaked it to go from 00 to 46 .... I encrypted again and had 46 TS.encrypted files.... But when I play the video (M3U8.encrypted) in the player, it stops after 0 min 36 sec.... which means it only plays 6 segments of 6 seconds.... If I change the HLS time to 10, it plays 1 minutes, so 6 segments of 10 seconds....

What else do I need to change to get it to play all the encrypted  segments present in the encrypted playlist ? 

PS: my goal is to be able to encrypt and play any videos of any length. Thanks in advance.
